### ISSUE TITLE
Cannot generate SBOM for same build id twice

### ISSUE THREAD

**Issue by goldmann** [project-ncl/sbomer#6]
Subsequent requests for SBOM generation fail with:

```
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "uq_sbom_buildid_strategy"
  Detail: Key (build_id, generation_mode)=(AXNV6QNVOSYAA, BASE_CYCLONEDX) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:190)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:152)
	at io.agroal.pool.wrapper.PreparedStatementWrapper.executeUpdate(PreparedStatementWrapper.java:88)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:197)
	... 47 more
```

**Comment by goldmann** [comment]
We can do that now!
